using System;using System.Collections.Generic;using System.Linq;using System.Text;using System.Threading.Tasks;using System.Data;namespace ConsoleApp1{    class Program    {
        public class num        {            int n;            double[] firstnum = new double[100];            double[] secondnum = new double[100];            double[] lastnum = new double[100];            double[] thirdnum = new double[100];            int[] flagnum = new int[100];            string[] op = new string[] { "+", "-", "*", "/" };            public num(int n)            {                this.n = n;            }            public void get()            {                Console.WriteLine("请输入计算题总个数： ");                n = int.Parse(Console.ReadLine());            }            public static float ClacByDataTable(string expression)
            {
                object result = new DataTable().Compute(expression, "");
                return float.Parse(result + "");
            }            public void create()            {                Random rand = new Random();                for (int i = 0; i < 100; i++)                {                    firstnum[i] = rand.Next(100);                    secondnum[i] = rand.Next(100);                    lastnum[i] = rand.Next(100);                    flagnum[i] = rand.Next(10);                    thirdnum[i] = rand.Next(100);                }                int count = 0;                float r=0;                string s;                for (int j = 0; j < 100; j++)                {

                    if (flagnum[j] % 2 == 0)                    {                        string opt = op[rand.Next(4)];                        string opt1 = op[rand.Next(4)];                        double first = firstnum[j];                        double second = secondnum[j];                        double last = lastnum[j];                        if (opt == "/" && opt1 == "/")                        {                            if ((first / second) % 1 == 0 && second != 0 && (second / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString()  + opt + second.ToString () + opt1 + last.ToString ();                                r = ClacByDataTable(s);
                                Console.WriteLine("{0} {1} {2} {3} {4} = {5}", first, opt, second, opt1, last,r);                                count++;                            }                        }                        else if (opt == "/" && opt1 != "/")                        {                            if ((first / second) % 1 == 0 && second != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);                                s = first.ToString() + opt + second.ToString() + opt1 + last.ToString();                                r = ClacByDataTable(s);
                                Console.WriteLine("{0} {1} {2} {3} {4} = {5}", first, opt, second, opt1, last, r);                                count++;                            }
                        }                        else if (opt1 == "/" && opt != "/")                        {                            if ((second / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);                                s = first.ToString() + opt + second.ToString() + opt1 + last.ToString();                                r = ClacByDataTable(s);
                                Console.WriteLine("{0} {1} {2} {3} {4} = {5}", first, opt, second, opt1, last, r);                                count++;                            }                        }                        else                        {                            Console.Write("第" + "{0}" + "道   :", count + 1);                            s = first.ToString() + opt + second.ToString() + opt1 + last.ToString();
                            r = ClacByDataTable(s);
                            Console.WriteLine("{0} {1} {2} {3} {4} = {5}", first, opt, second, opt1, last, r);                            count++;                        }                    }                    else                    {                        string opt = op[rand.Next(4)];                        string opt1 = op[rand.Next(4)];                        string opt2 = op[rand.Next(4)];                        double first = firstnum[j];                        double second = secondnum[j];                        double last = lastnum[j];                        double third = thirdnum[j];                        if (opt == "/" && opt1 == "/" && opt2 == "/")                        {                            if ((first / second) % 1 == 0 && second != 0 && (first / second / third) % 1 == 0 && third != 0 && (first / second / third / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);                                s = first.ToString() + opt + second.ToString() + opt1 +third .ToString ()+opt2+ last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last,r);                                count++;                            }                        }                        else if (opt == "/" && opt1 == "/" && opt2 != "/")                        {                            if ((first / second) % 1 == 0 && second != 0 && (first / second / third) % 1 == 0 && third != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r); ;                                count++;                            }                        }                        else if (opt != "/" && opt1 == "/" && opt2 == "/")                        {                            if ((second / third) % 1 == 0 && third != 0 && (second / third / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                                count++;                            }                        }                        else if (opt == "/" && opt1 != "/" && opt2 == "/")                        {                            if ((first / second) % 1 == 0 && second != 0 && (third / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                                count++;                            }                        }                        else if (opt1 == "/" && opt != "/" && opt2 != "/")                        {                            if ((second / third) % 1 == 0 && third != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                                count++;                            }                        }                        else if (opt1 != "/" && opt == "/" && opt2 != "/")                        {                            if ((first / second) % 1 == 0 && second != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                                count++;                            }                        }                        else if (opt1 != "/" && opt != "/" && opt2 == "/")                        {                            if ((third / last) % 1 == 0 && last != 0)                            {                                Console.Write("第" + "{0}" + "道   :", count + 1);
                                s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();                                r = ClacByDataTable(s);                                Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                                count++;                            }                        }                        else                        {                            Console.Write("第" + "{0}" + "道   :", count + 1);
                            s = first.ToString() + opt + second.ToString() + opt1 + third.ToString() + opt2 + last.ToString();
                            r = ClacByDataTable(s);
                            Console.WriteLine("{0} {1} {2} {3} {4} {5} {6} = {7}", first, opt, second, opt1, third, opt2, last, r);                            count++;                        }                    }                    if (count == n)                        j = 200;                }
            }        }        static void Main(string[] args)        {            int n;            Console.WriteLine("请输入计算题总个数： ");            n = int.Parse(Console.ReadLine());            num n1 = new num(n);            n1.create();            Console.ReadKey();        }    }}
